name: Unit Tests

on:
  pull_request:
    branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                python-version: '3.x'
            - name: Run Tests
              run: |
                export DISPLAY=:99
                Xvfb :99 &
                python3 -m unittest tests/*_test.py